TARGET = ToolbitDMM-linux-x64/ToolbitDMM

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	electron-packager ./src ToolbitDMM --platform=linux --arch=x64 --electronVersion=4.2.12


clean:
	rm -fr ToolbitDMM-linux-x64


.PHONY: all clean
