TARGET = ToolbitDMM-darwin-x64/ToolbitDMM.app

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	electron-packager ./src ToolbitDMM --platform=darwin --arch=x64 --electronVersion=4.2.12
	cp -r ToolbitDMM-darwin-x64 ./binary-releases/

clean:
	rm -fr ToolbitDMM-darwin-x64


.PHONY: all clean
