TARGET =

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	electron-packager ./src ToolbitDMM --platform=darwin --arch=x64 --electronVersion=4.2.12

clean:
	rm -fr ToolbitDMM-darwin-x64


.PHONY: all clean
