TARGET = build/_tbi.so

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d build ] || mkdir -p build
	cp ../../include/*.h build
	cp ../../include/module/*.h build
	cp ../../src/*.cpp build
	cp ../../src/module/*.cpp build
	cp ../../src/HIDAPI/linux/hid.c build
	cp tbi.i build
	cp setup_linux.py build
	cd build; swig -c++ -python tbi.i
	cd build; python setup_linux.py build_ext --inplace
	cp -u build/tbi.py build/_tbi.so samples

clean:
	rm -fr build


.PHONY: all clean
