TARGET = build/tbi.bundle

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d build ] || mkdir -p build
	cp ../../include/*.h build
	cp ../../include/module/*.h build
	cp ../../src/*.cpp build
	cp ../../src/module/*.cpp build
	cp ../../src/HIDAPI/mac/hid.c build
	cp ../tbi.i build
	cp extconf.rb build
	cd build; swig -c++ -ruby tbi.i
	cd build; ruby extconf.rb
	cd build; make
	cp -f build/tbi.bundle samples

clean:
	rm -fr build


.PHONY: all clean
