TARGET = build/tbi.so

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d build ] || mkdir -p build
	cp ../../include/*.h build
	cp ../../include/module/*.h build
	cp ../../src/*.cpp build
	cp ../../src/module/*.cpp build
	cp ../../src/hidapi/windows/hid.c build
	cp ../tbi.i build
	cp extconf.rb build
	cd build; swig -c++ -ruby tbi.i
	cd build; /mingw64/bin/ruby extconf.rb
	cd build; make
	cp -f build/tbi.so samples

clean:
	rm -fr build


.PHONY: all clean
